services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env.test
    ports:
      - 5433:5432
  node:
    container_name: node
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env.test
    depends_on:
      - postgres
